// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class IMInitSDKParam (
  val identityID: String,
  val sign: String,
  val nickName: String,
  val nickId: String,
  val device: String,
  val headIcon: String,
  val phone: String,
  val email: String,
  val langType: Long,
  val source: String,
  val extraInfo: Map<String?, String?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): IMInitSDKParam {
      val identityID = list[0] as String
      val sign = list[1] as String
      val nickName = list[2] as String
      val nickId = list[3] as String
      val device = list[4] as String
      val headIcon = list[5] as String
      val phone = list[6] as String
      val email = list[7] as String
      val langType = list[8].let { if (it is Int) it.toLong() else it as Long }
      val source = list[9] as String
      val extraInfo = list[10] as Map<String?, String?>?
      return IMInitSDKParam(identityID, sign, nickName, nickId, device, headIcon, phone, email, langType, source, extraInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      identityID,
      sign,
      nickName,
      nickId,
      device,
      headIcon,
      phone,
      email,
      langType,
      source,
      extraInfo,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object IMPluginApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IMInitSDKParam.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is IMInitSDKParam -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface IMPluginApi {
  fun getPlatformVersion(): String
  fun initSDK(param: IMInitSDKParam): Boolean

  companion object {
    /** The codec used by IMPluginApi. */
    val codec: MessageCodec<Any?> by lazy {
      IMPluginApiCodec
    }
    /** Sets up an instance of `IMPluginApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: IMPluginApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imchat_sdk_platform_interface.IMPluginApi.getPlatformVersion", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getPlatformVersion())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imchat_sdk_platform_interface.IMPluginApi.initSDK", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as IMInitSDKParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.initSDK(paramArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
