// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class IMInitSDKParam {
  IMInitSDKParam({
    required this.identityID,
    required this.sign,
    required this.nickName,
    required this.nickId,
    required this.device,
    required this.headIcon,
    required this.phone,
    required this.email,
    required this.langType,
    required this.source,
    this.extraInfo,
  });

  String identityID;

  String sign;

  String nickName;

  String nickId;

  String device;

  String headIcon;

  String phone;

  String email;

  int langType;

  String source;

  Map<String?, String?>? extraInfo;

  Object encode() {
    return <Object?>[
      identityID,
      sign,
      nickName,
      nickId,
      device,
      headIcon,
      phone,
      email,
      langType,
      source,
      extraInfo,
    ];
  }

  static IMInitSDKParam decode(Object result) {
    result as List<Object?>;
    return IMInitSDKParam(
      identityID: result[0]! as String,
      sign: result[1]! as String,
      nickName: result[2]! as String,
      nickId: result[3]! as String,
      device: result[4]! as String,
      headIcon: result[5]! as String,
      phone: result[6]! as String,
      email: result[7]! as String,
      langType: result[8]! as int,
      source: result[9]! as String,
      extraInfo: (result[10] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

class _IMPluginApiCodec extends StandardMessageCodec {
  const _IMPluginApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is IMInitSDKParam) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return IMInitSDKParam.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class IMPluginApi {
  /// Constructor for [IMPluginApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IMPluginApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _IMPluginApiCodec();

  Future<String> getPlatformVersion() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.imchat_sdk_platform_interface.IMPluginApi.getPlatformVersion', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<bool> initSDK(IMInitSDKParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.imchat_sdk_platform_interface.IMPluginApi.initSDK', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }
}
